sudo: required
services:
  - docker

before_install:
  - docker build -t scurrent/docker-react -f Dockerfile.dev .    # gives you back the id of the image, so tag it

#script:
#  - docker run scurrent/docker-react npm run test -- --coverage    #default npm run test hangs and gives you some options

script:
    - docker run -e CI=true scurrent/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-sc"
  env: "DockerSc-env"
  bucket_name: "elasticbeanstalk-us-east-1-432378262638"
  bucket_path: "docker-sc"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

